### ISSUE TITLE
Unable to enable Servo

### ISSUE THREAD

**Issue by pcider** [hans-robot/elfin_s_robot#1]
Hi, we are using ROS Noetic and we are running into intermittent issues with enabling the servos. We are using the robot model S20 on noetic branch.

Currently, we switch the robot from the teach pendant by doing an E-Stop, switching the ethercat cable from the teach pendant to a computer running Linux 5.15.163-rt78. We are able to run the elfin_ros_control node but sometimes we couldnt enable the servo / move the arm for no good reason. However, we are able to receive joint states and the position of the arm.

We could not seem to pinpoint the exact issue causing this, but we have done a packet capture on the ethercat interface using `tcpdump`. We attempted to enable the arm 3 times during the packet capture but all 3 times failed. Could you help us figure out what might be the cause of the issue?

[enable_servo.tar.gz](https://github.com/user-attachments/files/17100045/enable_servo.tar.gz)

Thanks

**Comment by Neverforgetlove** [comment]
I can't open this file, the file is damaged.

**Comment by pcider** [comment]
The file i sent was a tar archive. For now the issue is solved. I'll close this for now.
